package-lock.json, server/db/models/user.js
=> Seed branch

package-lock.json, server/db/models/product.js
=> Bryan dev branch

server/db/models/index.js
=> products model

script/productSeed.js
=> started working on seed

script/productSeed.js
=> product seed

server/db/models/index.js, server/db/models/order.js, server/db/models/product.js, server/db/models/purchases.js, server/db/models/user.js, server/index.js
=> finished associations

server/api/index.js, server/api/products.js, server/api/users.js
=> added tested users and product routes

server/db/models/index.js
=> more table stuff

server/api/index.js, server/api/products.js, server/api/users.js
=> added comments

script/orderSeed.js, script/purchaseSeed.js, script/seed.js, server/api/index.js, server/api/orders.js, server/db/models/purchases.js, server/db/models/user.js
=> purchase and order seed

server/db/models/category.js, server/db/models/index.js, server/db/models/review.js
=> Reviews model

server/api/orders.js, server/api/products.js, server/db/models/order.js
=> added changes to the order model

server/api/orders.js
=> fixed the thing

server/api/index.js, server/api/orders.js, server/api/products.js, server/api/users.js, server/db/models/category.js, server/db/models/order.js, server/db/models/product.js, server/db/models/review.js, server/index.js
=> cleaning up some code

client/components/AdminUser.js, client/components/AllProducts.js, client/components/Footer.js, client/components/Home.js, client/components/NavBar.js, client/components/SingleProduct.js, client/components/SingleUser.js, client/components/index.js, client/routes.js, client/store/allProducts.js, client/store/index.js, client/store/singleProduct.js
=> made basic boilerplate for front end components and store

package.json
=> installed material-ui

client/index.js, package-lock.json, public/index.html
=> added materialUi wrapper to main

client/components/SingleProduct.js, client/store/singleProduct.js
=> created singleProduct View Page

client/components/NavBar.js, client/components/main.js
=> added navbar and productPreview component

client/components/AllProducts.js, client/store/allProducts.js
=> All Products UI initial build

client/components/AllProducts.js
=> Style All Products UI

client/components/SingleProduct.js, client/store/singleProduct.js
=> editted singleProduct

script/index.js, server/db/models/product.js
=> User profile

client/components/Home.js, client/components/NavBar.js, client/components/ProductPreview.js
=> added more functionality to the appBar and homepage

client/components/ProductReviews.js
=> Product Reviews Component completed

client/components/ProductReviews.js, client/components/SingleProduct.js, client/store/singleProduct.js, server/api/products.js
=> working on singleProduct reviews

client/components/LoginForm.js, client/components/LoginFormContainer.js, client/components/NavBar.js, client/store/currentUser.js, client/store/index.js, public/style.css, server/api/index.js, server/auth/index.js
=> signup form is created and functional

client/components/LoginForm.js, client/components/NavBar.js, client/components/SignUpForm.js, client/components/SignUpFormContainer.js, client/components/main.js, client/routes.js, client/store/currentUser.js, client/store/index.js, server/index.js
=> login logout and signup are working

client/components/NavBar.js, server/db/models/user.js
=> changes user model validations and added google auth button to navbar

client/components/SingleProduct.js, client/store/index.js, client/store/productReviews.js, client/store/singleProduct.js
=> Vinitsbranch

client/components/Categories.js, client/components/NavBar.js, client/routes.js, client/store/currentUser.js, server/api/users.js, server/auth/google.js
=> google authorization works

server/api/categories.js, server/api/users.js
=> added route security to user routes

client/components/ProductReviews.js, package-lock.json, package.json
=> Added Rating to Product Reviews

client/components/AllProducts.js, client/components/Categories.js, client/components/LoginFormContainer.js, client/components/NavBar.js, client/components/ProductPreview.js, client/components/SignUpFormContainer.js, client/components/UserProfile.js, public/style.css, server/db/models/category.js, server/db/models/product.js, server/db/models/user.js
=> added web security and model validations

client/components/AllProducts.js, client/store/index.js
=> removed references to user in combine reducer

client/components/CartView.js, client/routes.js, client/store/activeOrder.js, client/store/index.js
=> created cartView for authenticated user

client/store/index.js
=> minor bug fix

client/store/index.js
=> updated combine reducer importing

client/components/CartView.js, client/routes.js, client/store/activeOrder.js, server/api/users.js
=> created more restful api route for authenticated user cart

client/components/AddToCart.js, client/components/CartView.js, client/store/activeOrder.js, server/api/users.js
=>  working on api route for adding products to cart

client/components/CartView.js, client/store/activeOrder.js, server/api/users.js
=> added remove item from user cart

server/api/users.js
=> finished update quantity for user cart

client/components/ProductReviews.js, client/components/SingleProduct.js, client/store/productReviews.js, package-lock.json, package.json, server/api/products.js
=> Post Product Reviews

client/components/CartView.js, client/store/activeOrder.js, server/api/users.js, server/db/models/index.js
=> finished update cart quantity for user

client/components/AllProducts.js, client/components/Categories.js, client/components/NavBar.js, client/components/UserProfile.js, client/routes.js, client/store/allProducts.js, server/api/products.js
=> Categories

client/components/CartView.js, client/store/activeOrder.js, server/api/orders.js
=> added checkout functionality to cart

client/components/NavBar.js, public/style.css
=> fixed navbar issues
